git:
  depth: false
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+\\.\\d+$/"

matrix:
  include:
    - name: "File merge benchmark"
      language: python
      os: linux
      python: 3.8
      install: bash .travis/install.sh
      # script placed by install.sh
      script: bash ~/.local/bin/run_benchmark.sh
    - name: "Unit tests"
      language: java
      os: linux
      jdk: openjdk8
      after_success: bash <(curl -s https://codecov.io/bash)

notifications:
  email: false

cache:
  directories:
    - $HOME/.m2
