git:
  depth: false

matrix:
  include:
    - language: python
      os: linux
      python: 3.8
      script: ".travis/run_benchmark.sh"
    - language: java
      os: linux
      jdk: openjdk8
      after_success: bash <(curl -s https://codecov.io/bash)

notifications:
  email: false

cache:
  directories:
    - $HOME/.m2
