git:
  depth: false

matrix:
  include:
    - name: "File merge benchmark"
      language: python
      os: linux
      python: 3.8
      install: bash .travis/install.sh
      # script placed by install.sh
      script: bash ~/.local/bin/run_benchmark.sh
    - name: "Merge-and-build benchmark"
      language: python
      os: linux
      python: 3.8
      # script placed by install.sh
      install: bash "$TRAVIS_BUILD_DIR"/.travis/install.sh
      script: bash ~/.local/bin/run_build_benchmark.sh
      addons:
         apt:
            packages:
               - openjdk-8-jdk
               - openjfx
    - name: "Unit tests"
      language: java
      os: linux
      jdk: openjdk8
      after_success: bash <(curl -s https://codecov.io/bash)

notifications:
  email: false

cache:
  directories:
    - $HOME/.m2
